version: "2.10.2"
services:
  back_end:
    build: ./back_end
    container_name: back_app
    ports:
      - '4000:8080'
    volumes:
      - ./back_end:/app
  front_end:
    build: ./front_end
    container_name: front_app
    ports:
      - '3000:3000'
    volumes:
      - ./front_end:/app
